title: GitHub Pages tutoria
author: Sabor117
email: s.may-wilson(at)ed.ac.uk
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: SebastianMayWi1 # DO NOT include the @ character, or else the build will fail!
github_username:  Sabor117 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
